#+TITLE: How to break through Algebraic Geometry
#+DATE: <2024-12-20 Fri>

* Prelude

Algebraic geometry is a beautiful subject, but its study is impenetrable to most of us. This was certainly the case for /me/. I was surprised to find myself studying it in late 2024. In this article I will detail how this came to be and what worked for me to help me approach this subject.

* Guidance from my muse

It's important to stay humble: One day I decided to study the [[https://en.wikipedia.org/wiki/Euclidean_algorithm][Euclidean algorithm]], because I wanted to solve a 3-factor RSA exercise. [fn:1] I've studied this algorithm many times before, but it had never "clicked", and so I would forget it after a month or so (or a day!). This time it was different. I took my time, and I thought more carefully about [[https://en.wikipedia.org/wiki/Euclidean_algorithm#/media/File:Euclid's_algorithm_Book_VII_Proposition_2_3.svg][this Wikipedia picture]] which completely illustrated the entire algorithm for me:

#+ATTR_HTML: :width 40% :height 40%
#+CAPTION: Two examples of Euclid's algorithm.
#+NAME: fig:euclid-algorithm
[[../img/euclid-algorithm.svg]]

The simplicity of the algorithm is incredible, as it is something that I've been subconsciously doing myself countless times in the past when fidgeting pieces of paper in my hands.

The Euclidean algorithm opened a door to more questions surrounding it, especially with regards to [[https://en.wikipedia.org/wiki/Elliptic_curve][elliptic curves]]. The miracle had happened earlier however: to view such a familiar concept under new light, completely elucidated, to finally /understand it/, is a bit shocking.

Armed with this newfound confidence that subjects that in the past were incomprehensible may become understandable today, I began sailing towards Algebraic Geometry.

[fn:1] [[https://2024.csc.tf/challenges][CyberSpace CTF 2024]], /"Modulus RSA"/.

* The first questions

The first question came form elliptic curves in cryptography, which I read that are curves in the space denoted by $\mathbb{PG}(2, q)$. Since I didn't know what this space is, I already had something that seemed foreign and fascinating: a promise of more geometric intuition if I were to understand the mathematics involved there.

This remained in the back of my head, probably causing some damage. In the meantime, I remembered an old observation that I had read in the past, namely that smooth manifolds $M$ are characterized by their ring of smooth functions $C^\infty(M)$, which is to say that everything about $M$ can be recovered from the algebraic structure of $C^\infty(M)$. I *knew* this were to be the case, but I didn't know *how*.

\begin{align}
\label{functor}
C^\infty(M) \xrightarrow{\text{?}} M
\end{align}

I also knew that I could find the answer in [cite:@nestruev-2020] and so I did. Chapter 4 contains a complete proof of existence of \eqref{functor}. I got hooked into these new definitions, such as the [[https://en.wikipedia.org/wiki/Spectrum_of_a_ring][spectrum of a ring]], and I wanted to learn more, so after finishing Chapter 4 I skipped straight to Chapter 8. Because of how this is all presented, I did not realize that I was already into modern Algebraic Geometry territory.

* A plethora of resources

Now that I had my first taste, I wanted to read more. Jumping straight to Chapter 2 of Vakil's notes [cite:@vakil-ag-2024], I found out what the definition of a sheaf is (always keeping in mind the ring of smooth functions $U\mapsto C^\infty(U)$ as an example), and Chapter 3 taught me a lot about the basics of $\Spec A$ (I also did some of the exercises). In Chapter 4 I learned about schemes. Somewhere in all that, I had to understand stalks better, and I figured out how categorical limits work by that example (mind you that I've tried many times in the past to understand categorical limits, but only now did they click). Other interesting concepts I picked up are the intuition behind $\Spec A/p$ and $\Spec A_p$, which I like to think of as the "geometry inside $p$" and the geometry over $p$ (respectively).

It was at that time when I decided that I wanted to once again ground myself to a more basic level of mathematics and I discovered the wonderful video lectures by Borcherds [cite:@borcherds-yt-2020]. I found even more exercises and lecture notes in James McKernan's 18.725 lecture notes
[cite:@mckernan-18.725-2009].

* References

#+print_bibliography:
